#!/bin/sh
##############################################################################
## Gradle start up script for POSIX generated by Gradle.
##############################################################################

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo "$*"
    exit 1
}

OS_NAME="`uname`"
case "$OS_NAME" in
    CYGWIN* | MINGW* | MSYS* )
        IS_WINDOWS=true
        ;;
    *)
        IS_WINDOWS=false
        ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if $IS_WINDOWS ; then
    # Use gradlew.bat on Windows
    exec "$APP_HOME/gradlew.bat" "$@"
else
    exec java $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
fi
